"""reset schema

Revision ID: 04619bc38545
Revises: 78a8f2021813
Create Date: 2026-02-02 20:26:34.263386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04619bc38545'
down_revision: Union[str, Sequence[str], None] = '78a8f2021813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.add_column('lokasi_konservasi', sa.Column('deskripsi', sa.Text(), nullable=True))
    op.alter_column('lokasi_konservasi', 'nama_lokasi',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('lokasi_konservasi_nama_lokasi_key'), 'lokasi_konservasi', type_='unique')
    op.create_index('idx_lokasi_konservasi_geom', 'lokasi_konservasi', ['geom'], unique=False, postgresql_using='gist')
    op.add_column('satwa', sa.Column('jenis', sa.String(length=50), nullable=True))
    op.add_column('satwa', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('satwa', sa.Column('gambar', sa.String(length=200), nullable=True))
    op.alter_column('satwa', 'nama_satwa',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('satwa_nama_satwa_key'), 'satwa', type_='unique')
    op.drop_column('satwa', 'jenis_satwa')
    op.drop_column('satwa', 'status_satwa')
    op.alter_column('satwa_lokasi', 'satwa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('satwa_lokasi', 'lokasi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('satwa_lokasi', 'lokasi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('satwa_lokasi', 'satwa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('satwa', sa.Column('status_satwa', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('satwa', sa.Column('jenis_satwa', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('satwa_nama_satwa_key'), 'satwa', ['nama_satwa'], postgresql_nulls_not_distinct=False)
    op.alter_column('satwa', 'nama_satwa',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('satwa', 'gambar')
    op.drop_column('satwa', 'status')
    op.drop_column('satwa', 'jenis')
    op.drop_index('idx_lokasi_konservasi_geom', table_name='lokasi_konservasi', postgresql_using='gist')
    op.create_unique_constraint(op.f('lokasi_konservasi_nama_lokasi_key'), 'lokasi_konservasi', ['nama_lokasi'], postgresql_nulls_not_distinct=False)
    op.alter_column('lokasi_konservasi', 'nama_lokasi',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('lokasi_konservasi', 'deskripsi')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
