"""Add deskripsi column to satwa

Revision ID: 467ef7434719
Revises: 04619bc38545
Create Date: 2026-03-08 13:25:40.367798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467ef7434719'
down_revision: Union[str, Sequence[str], None] = '04619bc38545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
        op.add_column('satwa', sa.Column('deskripsi', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'lokasi_konservasi', ['nama_lokasi'])
    op.add_column('satwa', sa.Column('deskripsi', sa.Text(), nullable=True))
    op.alter_column('satwa', 'nama_satwa',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('satwa_lokasi', 'satwa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('satwa_lokasi', 'lokasi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    def downgrade():
        op.drop_column('satwa', 'deskripsi')
    op.alter_column('satwa_lokasi', 'lokasi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('satwa_lokasi', 'satwa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('satwa', 'nama_satwa',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('satwa', 'deskripsi')
    op.drop_constraint(None, 'lokasi_konservasi', type_='unique')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
