"""add gambar column to satwa

Revision ID: 9b0a0c86f136
Revises: af7d4d91bd89
Create Date: 2026-01-19 22:35:06.278069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0a0c86f136'
down_revision: Union[str, Sequence[str], None] = 'af7d4d91bd89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('satwa', sa.Column('gambar', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('satwa', 'gambar')
    # ### end Alembic commands ###
