"""sync models

Revision ID: af7d4d91bd89
Revises: 
Create Date: 2026-01-19 21:50:27.975308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7d4d91bd89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lokasi_konservasi', sa.Column('deskripsi', sa.Text(), nullable=True))
    op.alter_column('lokasi_konservasi', 'nama_lokasi',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('lokasi_konservasi', 'latitude')
    op.drop_column('lokasi_konservasi', 'longitude')
    op.add_column('satwa', sa.Column('jenis', sa.String(length=50), nullable=True))
    op.add_column('satwa', sa.Column('status', sa.String(length=50), nullable=True))
    op.alter_column('satwa', 'nama_satwa',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('satwa', 'jenis_satwa')
    op.drop_column('satwa', 'status_satwa')
    op.alter_column('satwa_lokasi', 'satwa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('satwa_lokasi', 'lokasi_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('satwa_lokasi', 'lokasi_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('satwa_lokasi', 'satwa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('satwa', sa.Column('status_satwa', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('satwa', sa.Column('jenis_satwa', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('satwa', 'nama_satwa',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('satwa', 'status')
    op.drop_column('satwa', 'jenis')
    op.add_column('lokasi_konservasi', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lokasi_konservasi', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('lokasi_konservasi', 'nama_lokasi',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('lokasi_konservasi', 'deskripsi')
    # ### end Alembic commands ###
