"""add latitude longitude to LokasiKonservasi

Revision ID: cb39019369ab
Revises: 9b0a0c86f136
Create Date: 2026-01-19 22:39:27.095857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb39019369ab'
down_revision: Union[str, Sequence[str], None] = '9b0a0c86f136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lokasi_konservasi', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('lokasi_konservasi', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lokasi_konservasi', 'longitude')
    op.drop_column('lokasi_konservasi', 'latitude')
    # ### end Alembic commands ###
